defaultContentLanguage: en
title: Henning Dahlheim
baseURL: https://dahlheim.ch

languages:
  de:
    weight: 1
    LanguageName: German
    menu:
      main:
        - pageref: "/blog/"
          name: "Blog"
          weight: 1
        - pageref: "/projects/"
          name: "Projekte"
          weight: 1
      social:
        - url: https://github.com/hdahlheim
          name: GitHub
          weight: 1
        - url: https://bsky.app/profile/dahlheim.ch
          name: bluesky
          weight: 2
    params:
      description: Henning Dahlheim, Software Entwickler aus Basel
  en:
    weight: 1
    LanguageName: Englisch
    menu:
      main:
        - pageref: "/blog/"
          name: "Blog"
          weight: 1
        - pageref: "/projects/"
          name: "Projects"
          weight: 1
      social:
        - url: https://github.com/hdahlheim
          name: GitHub
          weight: 1
        - url: https://bsky.app/profile/dahlheim.ch
          name: bluesky
          weight: 2
    params:
      description: I’m a Software Developer based in Basel.

markup:
  goldmark:
    renderer:
      unsafe: true

build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json

pygmentsCodefences: true
pygmentsStyle: "dracula"
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
