defaultContentLanguage: en
title: Henning Dahlheim
baseURL: https://dahlheim.ch

languages:
  de:
    weight: 1
    LanguageName: German
    menu:
      main:
        - url: "/posts/"
          name: "Beiträge"
          weight: 1
      social:
      - url: https://github.com/hdahlheim
        name: GitHub
        weight: 1
      - url: https://twitter.com/hactar_
        name: twitter
        weight: 2
    params:
      description: Henning Dahlheim, Software Entwickler aus Basel
  en:
    weight: 1
    LanguageName: Englisch
    menu:
      main:
        - url: "/blog/"
          name: "Articles"
          weight: 1
      uses:
        - url: '/uses/'
          name: "Things I use"
          weight: 5
      social:
      - url: https://github.com/hdahlheim
        name: GitHub
        weight: 1
      - url: https://twitter.com/hactar_
        name: twitter
        weight: 2
    params:
      description: I’m a Software Developer based in Basel.

pygmentsCodefences: true
pygmentsStyle: "api"
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
