---
- name: Build hugo page
  hosts: localhost
  tasks:
  - name:
    command: yarn build
    changed_when: true
  - name: Build Site
    command: hugo --gc
    changed_when: true
- name: Deploy
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/public"
    ansistrano_deploy_to: "~/public_html/dahlheim.ch"
    ansistrano_keep_releases: 3
    ansistrano_allow_anonymous_stats: no
  roles:
  - { role: ansistrano.deploy }

